"""comentarios_ahora_tiene_fecha_hora

Revision ID: 88b7b1f63335
Revises: 5d62425f3531
Create Date: 2023-07-02 13:44:45.671082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b7b1f63335'
down_revision = '5d62425f3531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_hora', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.drop_column('fecha_hora')

    # ### end Alembic commands ###
