"""fecha_hora_agregado

Revision ID: 91e673b7bfb6
Revises: 20c530a9e760
Create Date: 2023-07-01 19:50:24.462906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91e673b7bfb6'
down_revision = '20c530a9e760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publicacion', sa.Integer(), nullable=False))
        batch_op.drop_constraint('comentario_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'publicacion', ['publicacion'], ['id'])
        batch_op.drop_column('pais')

    with op.batch_alter_table('publicacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_hora', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicacion', schema=None) as batch_op:
        batch_op.drop_column('fecha_hora')

    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pais', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comentario_ibfk_1', 'publicacion', ['pais'], ['id'])
        batch_op.drop_column('publicacion')

    # ### end Alembic commands ###
