"""001_tablas_publicacion_tema_comentario

Revision ID: a39d4c870fce
Revises: 
Create Date: 2023-07-03 18:02:50.283878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a39d4c870fce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('publicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autor', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('tema_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tema_id'], ['tema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autor', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.Column('id_publicacion', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentario')
    op.drop_table('publicacion')
    op.drop_table('tema')
    # ### end Alembic commands ###
