"""foto_de_perfil

Revision ID: c3351c0f20dd
Revises: c9eb03728d44
Create Date: 2023-07-04 22:41:29.497999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3351c0f20dd'
down_revision = 'c9eb03728d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.drop_column('perfil')

    # ### end Alembic commands ###
