"""comentarios_tienen_clave_foranea

Revision ID: efcadc9c0031
Revises: 91e673b7bfb6
Create Date: 2023-07-02 13:20:21.092929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'efcadc9c0031'
down_revision = '91e673b7bfb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_publicacion', sa.Integer(), nullable=True))
        batch_op.drop_constraint('comentario_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'publicacion', ['id_publicacion'], ['id'])
        batch_op.create_foreign_key(None, 'publicacion', ['descripcion'], ['id'])
        batch_op.drop_column('publicacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publicacion', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comentario_ibfk_1', 'publicacion', ['publicacion'], ['id'])
        batch_op.drop_column('id_publicacion')
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
